# # NGINX Config

# map $http_upgrade $connection_upgrade {
#     default upgrade;
#     ''      close;
# }

# server {
#     listen 8081;
#     server_name _;

#     location /health {
#         default_type application/json;
#         return 200 '{"status":"ok"}';
#     }

#     location / {
#         proxy_pass http://127.0.0.1:8080;
#         proxy_http_version 1.1;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection $connection_upgrade;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }


map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 8081;
    server_name _;

    location = /health {
        auth_request /_code_server_healthz;

        error_page 401 403 500 502 503 504 =503 @unhealthy;
        error_page 404 = @healthy;

        root /tmp/health-check-empty;
        try_files /nonexistent =404;
    }

    location = /_code_server_healthz {
        internal;

        proxy_pass http://127.0.0.1:8080/healthz;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";

        proxy_connect_timeout 2s;
        proxy_read_timeout 2s;
    }

    location @healthy {
        default_type application/json;
        return 200 '{"status": "ok"}';
    }

    location @unhealthy {
        default_type application/json;
        return 503 '{"status": "unhealthy"}';
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}